version: "3"
services: 
  mongodb:
    restart: unless-stopped
    image: 'mongo:latest'
    container_name: "mongodb"
    env_file:
      - db.env
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - backnet
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    image: gitea.ollioddi.dk/ollioddi/p3-dashboard-backend:1.0
    restart: unless-stopped
    container_name: "backend"
    depends_on:
      - mongodb
    env_file:
      -  db.env
    environment:
      - "SPRING_PROFILES_ACTIVE=dev-localdb"
      - "admin.username=admin"
      - "admin.password=admin"
      - "admin.email=admin@localhost"
      - "disable.auth=false"
    networks:
      - backnet
    healthcheck:
      test: curl --fail http://localhost:8080/actuator/health  || exit 1
      interval: 15s
      timeout: 5s
      retries: 6

  frontend:
    image: gitea.ollioddi.dk/ollioddi/p3-dashboard-frontend:1.0
    restart: unless-stopped
    container_name: "frontend"
    ports:
      - 8080:80
    networks: 
      - backnet
    labels:
      - traefik.enable=true
      - traefik.http.routers.p3.entryPoints=https
      - traefik.http.services.p3.loadbalancer.server.port=8080
      - traefik.http.routers.p3.rule=Host(`dashboard.ollioddi.dk`)
      - kop.bind.ip=192.168.20.50
volumes:
  db:
    driver:
      local

networks: 
  backnet:
    driver: bridge