version: "3.8"
services: 
  mongodb:
    image: 'mongo:latest'
    restart: unless-stopped
    container_name: "mongodb"
    environment:
      - 'MONGO_INITDB_DATABASE=dashboard-db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - backnet
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    restart: unless-stopped
    build: 
      context: ./backend
      target: backend
    container_name: "backend"
    depends_on:
      - mongodb
    profiles:
      - backend
    labels:
      org.springframework.boot.ignore: true
    networks:
      - backnet
    healthcheck:
      test: curl --fail http://localhost:8080/actuator/health  || exit 1
      interval: 15s
      timeout: 5s
      retries: 6

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      target: frontend
    container_name: "frontend"
    ports:
      - 80:80
    networks: 
      - backnet

volumes:
  db:
    driver:
      local

networks: 
  backnet:
    driver: bridge