version: "3"
services: 
  mongodb:
    image: 'mongo:latest'
    container_name: "mongodb"
    env_file:
      - dev.env
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - backnet

  backend:
  
    build: 
      context: ./backend
      target: backend
    container_name: "backend"
    depends_on:
      - mongodb
    env_file:
      -  dev.env
    environment:
      - "SPRING_PROFILES_ACTIVE=dev-localdb"
      - "admin.username=admin"
      - "admin.password=admin"
      - "admin.email=admin@localhost"
      - "disable.auth=false"
    networks:
      - backnet

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      target: frontend
    container_name: "frontend"
    ports:
      - 80:80
    networks: 
      - backnet

volumes:
  db:
    driver:
      local

networks: 
  backnet:
    driver: bridge