# syntax=docker/dockerfile:experimental
# Base image
FROM maven:3-eclipse-temurin-21-alpine as build
WORKDIR /workspace/app

# Copy source
COPY pom.xml .
COPY src src
# Run maven installer with cache enabled
RUN --mount=type=cache,target=/root/.m2 mvn -Dmaven.test.skip=true clean install

# Extract jar layers for docker optimization
RUN java -Djarmode=layertools -jar target/*.jar extract --destination target/extracted

# Run the extracted application
FROM maven:3-eclipse-temurin-21-alpine as backend
RUN addgroup -S demo && adduser -S demo -G demo
VOLUME /tmp
USER demo
ARG EXTRACTED=/workspace/app/target/extracted
WORKDIR /application
COPY --from=build ${EXTRACTED}/dependencies/ ./
COPY --from=build ${EXTRACTED}/spring-boot-loader/ ./
COPY --from=build ${EXTRACTED}/snapshot-dependencies/ ./
COPY --from=build ${EXTRACTED}/application/ ./
ENTRYPOINT ["java","-noverify","-XX:TieredStopAtLevel=1","-Dspring.main.lazy-initialization=true","org.springframework.boot.loader.JarLauncher"]